name: deploy Ali Oss
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install hexo-cli@4.3.1 -g
      - run: npm install yarn
      - run: yarn install
      - run: hexo g
      - run: ls
      - run: pwd
      - run: node -v
      - run: hexo -v
