name: deploy Ali Oss
on: [push]
jobs:
  Deploy-Ali-OSS-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install hexo-cli@4.3.1 -g
      - run: npm install yarn
      - run: yarn install
      - run: hexo g
      - name: upload files to OSS
      - uses: fangbinwei/aliyun-oss-website-action@v1
        with:
            accessKeyId: ${{ secrets.ALI_OSS_ACCESSKEYID }}
            accessKeySecret: ${{ secrets.ALI_OSS_ACCESSKEYSECRET }}
            bucket: xiaogezi-fun
            endpoint: oss-cn-beijing.aliyuncs.com
            folder: public
